### ISSUE TITLE
Generated report is lacking elements

### ISSUE THREAD

**Issue by Zack24441** [IBMa/equal-access#460] opened 2021-07-07 18:04 UTC
## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`

## Summary

Hi,

I have problem with generating html report from getCompliance method using Node and playwright (I tried puppeteer but I end up with the same result). Problem is that html report is missing some additional files:
![image](https://user-images.githubusercontent.com/21018629/124806930-86b69f80-df5d-11eb-9a77-749f8cf5652f.png)

Probably I'm doing something wrong. Could please help with that?
## Relevant information
Version:
"playwright": "^1.12.3",
"accessibility-checker": "^3.1.8",

Code:
```
let content = await testPage.content();
await aChecker.getCompliance(content, 'myLabel');
await aChecker.close();
```
aceconfig.js:
```
module.exports = {
    ruleArchive: "latest",
    policies: ["IBM_Accessibility"],
    failLevels: ["violation", "potentialviolation"],
    reportLevels: [
        "violation",
        "potentialviolation",
        "recommendation",
        "potentialrecommendation",
        "manual",
        "pass",
    ],
    outputFormat: ["html"],
    label: [process.env.TRAVIS_BRANCH],
    outputFolder: "results",
    baselineFolder: "test/baselines",
};
```

**Comment by tombrunet** [comment] 2022-01-27 21:38
@Zack24441 It's not clear from this issue what is lacking. Can you elaborate? There were some issues that had been fixed. Are you still seeing this issue?

**Comment by aliunwala** [comment] 2022-02-07 20:40
Closing cannot reproduce.

**Closed by aliunwala** 2022-02-07 20:40 UTC
Labels: question
