### ISSUE TITLE
[BUG] It is not a real  a11y issue  about the id “AJAX_CONTAINER” in use

### ISSUE THREAD

**Issue by Wangdc104** [IBMa/equal-access#445] opened 2021-06-08 07:53 UTC
## What tool(s) are you using?
- [x] **`IBM Equal Access Accessibility Checker browser extension**
https://www.ibm.com/able/toolkit/verify/automated

## Detailed description

> Node version: 3.1.7
> Platform: Firefox

> Describe in detail the issue you're having.
It reports a lot of violations about -> The <div> element has the id “AJAX_CONTAINER” that is already in use.  
However, it is not a real accessibility issue and the JAWS still works correctly.

## Steps to reproduce the issue

**Got this issue while testing the IBM Security Verify Governance - Identity Manager** 

1. go to https://9.37.237.42:9082/itim/console/main
2. log in with itim manager/Secret@1233. 
3.Click the View Requests -  View All Requests  link in left navigation 
4.Use Accessibility Checker to scan 
The reproduce process pls refer to screen shot

The issue is The <div> element has the id "AJAX_CONTAINER" that is already in use.
Expected: Element 'id' attribute values must be unique within a document.

## Additional information

- Screenshots or code
![console View Requests - View All Requests 05](https://user-images.githubusercontent.com/60640166/121143662-decf8880-c86f-11eb-9cdb-e1fc8c25f3db.png)

- Observation:  (feedback from product developers, vshet@us.ibm.com)

“AJAX_CONTAINER” ID is needed to load the ajax content on the web page dynamically. This ID is also referred in code to address the element. This is the common functionality and fix is in PS-Web ( a third party framework). PS-Web is very old IBM library and right now they are not providing support for it. Also scope of this change is large.As this particular <div> element is not related to any UI element that involves user interaction, we are wondering whether it is really an accessibility issue or can it be ignored for now. These html elements are hidden and used internally to make async server calls.If required, we can have a call to discuss in detail.

**Comment by tombrunet** [comment] 2021-06-15 14:50
This rule is working as designed. HTML spec requires that ids are unique. When ids are not unique, the references are ambiguous. If the id isn't being referenced, then it shouldn't be there. If it is being referenced, which of the elements are you actually referring to?

The error triggers on elements when document.getElementById("AJAX_CONTAINER") results in a node other than the node that has that id. Closing since this is working as designed.

**Closed by tombrunet** 2021-06-15 14:50 UTC
Labels: Bug
