### ISSUE TITLE
Backticks not supported in message 'headings' displayed in Checker - 3672

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#602] opened 2022-01-07 22:42 UTC
Issue created by Mike:
Based on a review with Josiah, noticed that something formatted `"value"` was not being formatted properly in the messages headings displayed in the Checker, although supported in the Help content in the body.

The backticks should cause the information to display in a 'coding' font, i.e., fixed width.
But the formatting in the headings seems to be getting dropped. 
Currently the message text in the Checker browser extension 'headings' area does NOT come from the .mdx where backticks are supported, but come from the messages in the ...nls/index.ts file where backticks are NOT (currently) supported.  No known support for formatting in the messages in the .../nls/index.ts file. 

In the following image, the heading text "listitem" should be in a different font, just as the word 'role' is in a different font in the first line of the Why is this important? section. 

![image](https://media.github.ibm.com/user/1900/files/16b24980-2b4a-11ec-9443-7c0246122169)

 Need to confirm whether this is expected behaviour, and if any documented process needs to change.
 
 
Link to original issue:
https://github.ibm.com/ibma/e2e/issues/3672
Image of original issue:
![image](https://user-images.githubusercontent.com/4451128/148616691-2d0e3740-9969-45ba-bea8-568ddcb93c56.png)

**Comment by aliunwala** [comment] 2022-01-07 22:44
There are a few too many comments to replicate them here. Please see the image above for the comment's thread.

**Comment by aliunwala** [comment] 2022-01-11 21:06
Triage meeting notes:
Prioritize after looking at node 16, then have dev investigate

**Comment by MHoov** [comment] 2024-05-13 17:05
@tombrunet moving to Release Backlog since the last comment was to revisit after Node 16

**Comment by tombrunet** [comment] 2024-06-26 15:07
Closing this as working as designed. The messages used in the help headings are used in a wide variety of contexts - not just markdown. Yes, they are in the help, but they are also in JSON files, excel reports, HTML reports, consumed by other tools, etc. It's a fairly significant impact. If there's a larger justification, we can revisit, but that will require an impact and design evaluation as first steps.

**Closed by tombrunet** 2024-06-26 15:07 UTC
Labels: engine, priority-3 (low), development
