### ISSUE TITLE
[BUG]: aChecker crashing - window.ace.Checker is not a constructor

### ISSUE THREAD

**Issue by gdelory** [IBMa/equal-access#713] opened 2022-02-28 06:06 UTC
### Project

a11y checker engine, a11y checker

### Browser

Chrome

### Operating system

Other

### Description

The achecker npm tool is crashing. here is the full console:

[console.txt](https://github.com/IBMa/equal-access/files/8150944/console.txt)

### Steps to reproduce

Run achecker on the files in [this zip](https://ibm.box.com/s/rr1w30mut32qkwjn7mobw6xkevqzzy7x)

**Comment by tombrunet** [comment] 2022-02-28 18:15
Dupe of https://github.com/IBMa/equal-access/issues/331 . af03890_.html defines an element with `id="ace"`, which gets assigned to a javascript global variable, causing problems for our engine. Tracking this under #331.

**Closed by tombrunet** 2022-02-28 18:15 UTC
