### ISSUE TITLE
Information on plugin & .csv file diverge from HTML report 

### ISSUE THREAD

**Issue by cponara** [IBMa/equal-access#1014] opened 2022-07-26 16:31 UTC
Hello,
When I download the report generated by the plugin, I see different numbers for current status percentage and number of violations. 
Also, when a colleague runs the plugin on the same page, they get a different amount of violations. 
We both are using Google Chrome. Another colleague that's using Firefox gets the same results as me.

Plugin on my browser:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/34479043/181040938-15204489-2b39-4453-ba3f-e3e9d86f0c74.png">

Same info on .csv file:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/34479043/181043328-5801c3ef-3c5c-419b-a410-ffe6e837558f.png">

My HTML report (genrated & open on chrome):
<img width="300" alt="image" src="https://user-images.githubusercontent.com/34479043/181041266-5adc0db7-8a92-4ecc-ab41-1442e4597192.png">

My colleague's HTML report:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/34479043/181041479-4a8e9600-1cc4-408b-848f-ea161be80534.png">

Thank you for your help!

**Comment by tombrunet** [comment] 2022-07-26 17:09
@drjoho - Seeing the score difference with http://www.altoromutual.com/ test site also.

@cponara - If the archive and policies are the same (see extension options)... Regarding the difference in violation count, it would be worth identifying which violation is different. Historically (if same archive) that difference has always been due to a difference in the DOM being scanned. Sometimes its because of an extension installed that's injecting content into the DOM. Sometimes it's an ad or other injected content that's not the same.

As for the % scoring, there have been some fixes recently with regard to counting non-violation nodes, and that fix may not have been adjusted in the HTML report.

**Comment by cponara** [comment] 2022-07-27 16:03
hi @tombrunet thanks for the explanation, we'll compare the reports.

**Comment by tombrunet** [comment] 2022-07-27 17:01
Reopening this for us to look at the score issue between the extension and the saved report.

**Comment by aliunwala** [comment] 2022-07-28 20:09
Trigae:
Looks like we are able to reproduce this at-least running this on Altoro Mutual.

@drjoho will look like this in a future sprint. He thinks that it is just a place were the number is not updated correctly in html version correctly (But is updated correctly in the excel version).

**Comment by tombrunet** [comment] 2023-03-30 13:33
I cleaned up all of the scoring in our code refresh. This should all be fixed once this PR is merged and new release is complete.
https://github.com/IBMa/equal-access/pull/1371

**Closed by tombrunet** 2023-03-30 13:33 UTC
Labels: extension-checker, priority-3 (low), development
