### ISSUE TITLE
[BUG] Possible false positive on the 1.3.1 Info and Relationships 

### ISSUE THREAD

**Issue by Paul-Grogan** [IBMa/equal-access#254] opened 2020-10-12 16:40 UTC
There might be a false positive on "Verify that this ungrouped checkbox input is not related to other checkboxes"
The "What to do" for this check instructs

> OR, disassociate unrelated controls or controls of different types by using different "name" attribute values.

This is what we've attempted to do, but the Needs Review continues to get produced.

## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`
- [ ] `other`

## Detailed description

> Node version:
> Platform: 

Windows10, using Firefox (81.0.1) and Chrome (Version 85.0.4183.121) plugins.
Reproduced in macOS Cataline 10.15.4 using Firefox (81.0.1) and Chrome (Version 85.0.4183.121) plugins.

> Describe in detail the issue you're having.
We have a table with a column of Checkboxes, being used as row selectors.
The checkboxes have unique names, for example 
- name="d-231_table-item-renderer_2:0:741ea28f-b9fc-8c8f-cff4-ab1e6e74d3f9_checkbox"
Even with this unique "name", there's still one Needs Review produced for each row in the table.

The HTML, which does use custom elements, is similar to the following example, with the Needs Review being produced on the <input> element.

`<table-item-renderer role="rowgroup" id="d-276_tableItemRenderer" ........... >

	<div class="cellContainer" role="row">

		<div role="gridcell" class="cell................>

			<af-carbon-checkbox id="d-231_table-item-renderer_2:0:741ea28f-b9fc-8c8f-cff4-ab1e6e74d3f9" class="af-carbon-checkbox" title="the title here" aria-labelledby="d-276_tableItemRenderer">
				<div class="bx--form-item bx--checkbox-wrapper">
					<input type="checkbox" id="d-475-input" class="bx--checkbox" name="d-231_table-item-renderer_2:0:741ea28f-b9fc-8c8f-cff4-ab1e6e74d3f9_checkbox" value="1925775938">
					<label for="d-475-input" class="bx--checkbox-label">
						<span class="bx--checkbox-label-text bx--visually-hidden">the name here</span>
					</label>
				</div>
			</af-carbon-checkbox>
		</div>
	<div class="cell d-231-cell noWrap"............. other cells in the row.`

Notice the 'name' on the input checkbox. Other examples are 
- d-231_table-item-renderer_5:0:acb25d58-4fc6-f5f9-8cf6-a1903c8090fa_checkbox
- d-231_table-item-renderer_9:0:6899c0ba-3c33-6543-73b1-974f9aec26d0_checkbox

Even with these randomised names, the Needs Review for each row in our table is still produced.

Is there a bug that's producing a False Positive?

**Comment by sharitrewin** [comment] 2020-10-14 03:21
@Paul-Grogan it is still possible to get this issue even with unique names for the checkboxes, so yes there's a bug in the help instruction - it shouldn't be recommending unique names as a solution.
In general, this rule will fire if there are multiple checkboxes that potentially ought to be grouped, so you can check them.
However, if your checkboxes are in a data table the rule shouldn't fire. Could you please share what your table element looks like?

**Comment by Paul-Grogan** [comment] 2020-10-14 11:16
Hi @sharitrewin , here's a screenshot of the table. 
![000748](https://user-images.githubusercontent.com/70535014/95981454-9235c980-0e16-11eb-9138-4a021ab77abe.png)


The code sample in my original comment is for one of the Checkbox cell, I omitted the rest of the row and table. If that's not sufficient let me know and I'll try make an example that's not as large as this test table.

**Comment by sharitrewin** [comment] 2020-10-16 19:02
@Paul-Grogan, you are getting these issues because the checker is not able to detect that the checkboxes are in a table. Is the table marked up as a `<div role="grid">`? If so, you might consider using <table> instead. That should make these 'Needs Review' items go away.  Here are a couple of articles you might be interested in:

* [It's still ok to use tables](https://adrianroselli.com/2017/11/hey-its-still-ok-to-use-tables.html)
* [ARIA-grid as an anti-pattern](https://adrianroselli.com/2020/07/aria-grid-as-an-anti-pattern.html#Data)

That said, @tombrunet should WCAG20_Input_RadioChkInFieldSet treat checkboxes in a grid in the same way as checkboxes in a table?

**Comment by Paul-Grogan** [comment] 2020-10-19 08:40
Hi Shari,
Yes, we do have the table marked up as `<div role="grid">`.

I'll bring the use of `<table>` up with the team to discuss.

**Comment by Destop-Trang1801** [comment] 2020-10-31 17:08
[markdown-cheatsheet-online.pdf](https://github.com/IBMa/equal-access/files/5469470/markdown-cheatsheet-online.pdf)

**Comment by Destop-Trang1801** [comment] 2020-10-31 17:09
![accept-post-as-solution](https://user-images.githubusercontent.com/71356084/97785234-60728000-1bd6-11eb-8750-0287bd40817e.gif)


> There might be a false positive on "Verify that this ungrouped checkbox input is not related to other checkboxes"
> The "What to do" for this check instructs
> 
> > OR, disassociate unrelated controls or controls of different types by using different "name" attribute values.
> 
> This is what we've attempted to do, but the Needs Review continues to get produced.
> 
> ## What tool(s) are you using?
> * [ ]  `accessibility-checker-engine`
> * [x]  `accessibility-checker`
> * [ ]  `karma-accessibility-checker`
> * [ ]  `rule-server`
> * [ ]  `boilerplates`
> * [ ]  `other`
> 
> ## Detailed description
> > Node version:
> > Platform:
> 
> Windows10, using Firefox (81.0.1) and Chrome (Version 85.0.4183.121) plugins.
> Reproduced in macOS Cataline 10.15.4 using Firefox (81.0.1) and Chrome (Version 85.0.4183.121) plugins.
> 
> > Describe in detail the issue you're having.
> > We have a table with a column of Checkboxes, being used as row selectors.
> > The checkboxes have unique names, for example
> 
> * name="d-231_table-item-renderer_2:0:741ea28f-b9fc-8c8f-cff4-ab1e6e74d3f9_checkbox"
>   Even with this unique "name", there's still one Needs Review produced for each row in the table.
> 
> The HTML, which does use custom elements, is similar to the following example, with the Needs Review being produced on the element.
> 
> `<table-item-renderer role="rowgroup" id="d-276_tableItemRenderer" ........... >
> 
> ```
> <div class="cellContainer" role="row">
> 
> 	<div role="gridcell" class="cell................>
> 
> 		<af-carbon-checkbox id="d-231_table-item-renderer_2:0:741ea28f-b9fc-8c8f-cff4-ab1e6e74d3f9" class="af-carbon-checkbox" title="the title here" aria-labelledby="d-276_tableItemRenderer">
> 			<div class="bx--form-item bx--checkbox-wrapper">
> 				<input type="checkbox" id="d-475-input" class="bx--checkbox" name="d-231_table-item-renderer_2:0:741ea28f-b9fc-8c8f-cff4-ab1e6e74d3f9_checkbox" value="1925775938">
> 				<label for="d-475-input" class="bx--checkbox-label">
> 					<span class="bx--checkbox-label-text bx--visually-hidden">the name here</span>
> 				</label>
> 			</div>
> 		</af-carbon-checkbox>
> 	</div>
> <div class="cell d-231-cell noWrap"............. other cells in the row.`
> ```
> 
> Notice the 'name' on the input checkbox. Other examples are
> 
> * d-231_table-item-renderer_5:0:acb25d58-4fc6-f5f9-8cf6-a1903c8090fa_checkbox
> * d-231_table-item-renderer_9:0:6899c0ba-3c33-6543-73b1-974f9aec26d0_checkbox
> 
> Even with these randomised names, the Needs Review for each row in our table is still produced.
> 
> Is there a bug that's producing a False Positive?

**Comment by MHoov** [comment] 2021-06-01 20:26
As of June 1
- [x] general rule description (SME & Dev)
- [ ] testcases written (Dev)
- [ ] rule bug (Dev)
- [x] message written (SME)
- [x] help written (SME)

**Comment by tombrunet** [comment] 2021-12-02 19:24
Tried to reproduce this here - https://codesandbox.io/s/issue-254-00qun - but the rule does not trigger. I recall something was fixed in this space. Are you still getting these errors?

**Comment by tombrunet** [comment] 2021-12-03 16:02
Thank you

**Closed by tombrunet** 2021-12-03 16:02 UTC
Labels: Bug, Engine
