### ISSUE TITLE
[BUG]: Color contrast computation incorrect with shadow DOM

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#687] opened 2022-02-14 17:42 UTC
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Description

Reported by Ariella Gilmore.

Checker is reporting contrast violations with the callouts. Looks like this may be computing something incorrectly due to shadow dom, but may be color tokens. Need more investigation.

### Steps to reproduce

* Open https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/iframe.html?id=components-callout-quote--default

Two contrast violations are triggered. When using the color contrast analyzer, these both look fine. Something appears to not be calculating correctly.

**Comment by aliunwala** [comment] 2022-02-24 21:26
From Triage:
![image](https://user-images.githubusercontent.com/4451128/155610393-b22811c4-d9d6-4e56-a0d4-2938aedcbd3c.png)
![image](https://user-images.githubusercontent.com/4451128/155610494-d863f3de-ef10-4919-955f-2ab0482196b2.png)

**Comment by tombrunet** [comment] 2022-03-16 21:04
Recheck after #742

**Comment by marcjohlic** [comment] 2022-03-31 18:51
Moving this back into Triage for validation now that #742 has been merged

**Comment by shunguoy** [comment] 2022-04-04 14:54
the issue exists with two color contrast violations per version 3.1.25

**Comment by shunguoy** [comment] 2022-04-04 16:21
probably walking a shadow dom for the wrong parents.

**Comment by shunguoy** [comment] 2022-06-23 15:29
issue still the same with the fix in #826

**Comment by snidersd** [comment] 2022-06-28 16:13
Investigating issue. Unable to create a test case. This only happens during runtime.

**Comment by shunguoy** [comment] 2022-06-29 16:21
investigated the cause of the issue: the text elements are rendered under a shadow dom slot element, rather than in the light DOM.  The current color contrast logic doesn't support the shadow DOM tree.

**Comment by shunguoy** [comment] 2022-06-30 16:07
creating local test cases to replicate and fix error

**Comment by shunguoy** [comment] 2022-07-01 15:32
the error can be duplicated with a smaller shadow dom test without web component

**Comment by shunguoy** [comment] 2022-07-12 14:10
The initial rule logic is written but needs to test in various cases.

**Comment by shunguoy** [comment] 2022-07-14 18:14
test case: https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/iframe.html?id=components-callout-quote--default.   A live test is required in a browser.

**Comment by eirckr** [comment] 2022-07-29 18:34
@shunguoy violations are still present: 
<img width="1485" alt="Screen Shot 2022-07-29 at 1 33 12 PM" src="https://user-images.githubusercontent.com/62436670/181823055-5518806c-2de3-4775-97ca-c6e6df48c60f.png">

**Comment by shunguoy** [comment] 2022-07-29 21:00
@eirckr  do you rebuild the rule server from the branch?

**Comment by eirckr** [comment] 2022-08-01 16:20
Validated 
<img width="1479" alt="Screen Shot 2022-08-01 at 11 20 28 AM" src="https://user-images.githubusercontent.com/62436670/182196705-99d5125d-3cef-406e-bba2-bc0d1d7d3d19.png">

**Closed** 2022-08-01 16:21 UTC
Labels: Engine, priority-2 (med), reproducible, Ready for QA
