### ISSUE TITLE
[BUG] Content is not within a landmark element (unless it's owned by content that is in a landmark)

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#283] opened 2020-12-02 17:04 UTC
This is both a bug and a feature request. :)

Sometimes, overflow menus are added to tables or other containers where the menu popup cannot be inserted into its natural place in the DOM order without causing rendering problems. In these cases, a "floating" popup is added to the DOM somewhere else (often near the end of the body, and not usually inside any landmark). Of course, Accessibility Checker flags these as needing to be inside a landmark.

Authors can use [aria-owns](https://w3c.github.io/aria/#aria-owns) on the menu trigger button's parent (which can simply be a wrapper div) to get the browser to place the popup right after the trigger button in the accessibility tree, essentially creating the correct reading order for screen reader users (even though the DOM order is incorrect).

It would be great if Accessibility Checker could detect this, so that developers don't try to bend over backwards to cram the popup into a landmark just to make the violation go away.

The algorithm would go something like:
- if there's an element that's not in a landmark
   - if that element has an id
      - if that id is in an `aria-owns` of another element, and that other element is in a landmark
         - then the element is actually considered to be in a landmark, so violation is not needed

To test this, you can use the following steps:
1. [Open a sandbox on a Carbon overflow menu](https://rt5tq.csb.app/)
   - if that doesn't work (not sure if these code sandbox links are always valid) then go to [Carbon's Overflow Menu](https://www.carbondesignsystem.com/components/overflow-menu/usage/) and click on the first Sandbox link. Then find the icon button for "Open in new window" and click that.
2. Open DevTools (I'm using Chrome)
3. Add `role="main"` to the `<div id="root">`
    ![image](https://user-images.githubusercontent.com/3331913/100900249-a4d09480-3490-11eb-91e4-a20b77529b63.png)
4. Click on the overflow menu's trigger button to open the popup menu.
5. Run the Accessibility Checker.
    - note the "Content is not within a landmark element" violation for each menu item
6. Now add `id="popup"` to the `<ul role="menu">` and add `aria-owns="popup"` to the `<div id="root" role="main">`
    - (nobody would ever really use the main as a menu wrapper, but this is just for testing)
7. Take a look at the browser's Accessibility Tree (screen snapshot below)
    - (Chrome lazily calls the menu button a "combobox" - they really ought to call it a menu button, but whatever)
    - Note that the popup menu now follows the menu trigger button in the Accessibility Tree for the trigger button's parent
8. Now run Accessibility Checker
    - This is the point at which I'd like to see those violations go away. The popup menu is "in a landmark" (the main) for all intents and purposes - certainly as far as the browser and screen reader are concerned. Maybe a validation tool is not expected to look this deeply... in which case this is a feature request. Or maybe tools are expected to have as few false positives as possible... in which case this is a bug report. :)

#### For points 6 and 7: Chrome Accessibility Tree (in Elements panel's Accessibility subpanel) showing the effect of aria-owns
![image](https://user-images.githubusercontent.com/3331913/100903716-38579480-3494-11eb-90e4-bcf4590ab9a7.png)

**Comment by tombrunet** [comment] 2022-02-07 20:58
Something strange going on with this rule. See https://codesandbox.io/s/issue-283-2em4h?file=/index.html . The first div isn't flagged, but the second is.

**Comment by marcjohlic** [comment] 2022-02-14 19:25
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Equal-Access-61ae71f9f8b4ec001e136462/issues/IBMa/equal-access/283?planning-poker) with ZenHub @aliunwala @mbgower @shunguoy @tombrunet @philljenkins @drjoho

**Comment by marcjohlic** [comment] 2022-03-25 15:12
I don't see any updates or status on this one - it doesn't look like it's been started (or worked on for 20+ days).  Removing Ali and adding this back to Triage.

**Comment by shunguoy** [comment] 2022-04-04 15:27
reproducible with errors, but not sure if they are landmark issues.   
https://www.carbondesignsystem.com/components/overflow-menu/usage
  click an overflow menu in the page:

<img width="1945" alt="Screen Shot 2022-04-04 at 10 26 03 AM" src="https://user-images.githubusercontent.com/18539498/161578106-f64f7273-471c-4032-be28-d42eb571e730.png">

**Comment by marcjohlic** [comment] 2022-04-07 14:31
This one was not completed in R4.0.2 and we don't have anyone to work on it in R4.0.3.  Queuing it up for a future release.  I'm going to try to clear the Sprint and other metadata so that ZH stops tracking it in this release.

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/63b696b8-1609-49b5-80d0-74a2bfee9df1)

**Comment by aparnacyanam** [comment] 2022-07-01 13:48
Is there any update on this or expected time for this to be fixed? Multiple bugs about this are reported for our UI. Thank you!!

**Comment by tombrunet** [comment] 2022-07-01 15:38
@aparnacyanam We fixed several things related to aria-owns with the June 10 release. The testcases listed in this issue no longer fail as a result of that work. Please make sure you're not using an older archive. If you're still encountering issues, please open a new issue. Closing this one since it was already fixed.

**Closed by tombrunet** 2022-07-01 15:38 UTC
Labels: Bug, Engine, priority-2 (med), development
