### ISSUE TITLE
[A11y_Bug]: Unable to tab in to learn more from a scan results in Mac Firefox browser

### ISSUE THREAD

**Issue by eirckr** [IBMa/equal-access#685] opened 2022-02-11 17:20 UTC
### Project

a11y checker

### Browser

Firefox

### Operating System

MacOS

### Description

After we conduct a scan in the Firefox browser, the user in not able to tab in to learn more section. 

### Steps to reproduce

1. From Mac FF browser conduct a scan
2. From the results of the scan navigate with tabs into 'Learn more' 

User is unable to navigate to lear more.

**Comment by drjoho** [comment] 2022-04-01 21:10
Have been able to reproduce the issue. Can tab fine to "learn more" in Chrome. CANNOT tab to "learn more" in FireFox.

**Comment by drjoho** [comment] 2022-04-05 18:07
It turns out that this is an OS user setting problem in that Mozilla reads the keyboard preferences and on the Mac tabbing to focus via keyboard is not the default. So, Mozilla is being true to operating system settings in Mac OS.
There are two distinct ways around this on the user side. Both seem to work:
In System Preferences → Keyboard, in the Shortcuts pane, check the “Use keyboard navigation to move focus between controls"  checkbox at the bottom.
In Firefox, type "about:config" in the URL bar. There is no accessibility.tabfocus preference on the mac, so you'll have to make one. Right click in the window, create a new "integer" pref, and set it to 7.
Neither of these are terribly obvious. Also, neither of these are a server-side solution for developers, which is frustrating.

I just opened up Mac keyboard preferences and checked the bottom option:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/64442976/161821421-5e9be1ff-dee7-4cd6-9137-5aed28a75a17.png">

**Comment by drjoho** [comment] 2022-04-05 18:08
@eirckr ready for QA

**Comment by drjoho** [comment] 2022-04-06 22:24
Closing since there are no changes to the code. Users must change a setting in their OS.

**Closed by drjoho** 2022-04-06 22:24 UTC
Labels: extension, priority-2 (med), Ready for QA
