### ISSUE TITLE
[A11y_Bug]: DDS footer is incompatible with Accessibility checker

### ISSUE THREAD

**Issue by zrebec** [IBMa/equal-access#1207] opened 2022-12-20 07:50 UTC
### Project

other

### Browser

Chrome

### Operating System

MacOS

### Automated testing tool and ruleset

IBM Accessibility Checker - Latest version

### Description

We have in index.html this implementation for the footer

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="theme-color" content="#000000" />
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
    
    <title>Client Access Manager</title>

    <script
      src="//1.www.s81c.com/common/stats/ibm-common.js"
      async="async"></script>

    <script
      type="module"
      src="https://1.www.s81c.com/common/carbon-for-ibm-dotcom/tag/v1/latest/footer.min.js"
    ></script>

    
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    <dds-footer-container size="micro"> </dds-footer-container>
  </body>
</html>
```

In IBM accessibility checker I have this violiation for dds-footer:
- The value "input" of the 'for' attribute is not the 'id' of a valid <input> element
- Multiple elements with "navigation" role do not have unique labels (2 times)

### Steps to reproduce

Try implement <dds-footer-container size="micro"> </dds-footer-container> in some of your react HTML page (like index.html) and run IBM accessibility checker

**Comment by aliunwala** [comment] 2023-01-05 21:20
From the triage meeting:

We need to investigate this a bit further we were able to reproduce it here:
![image](https://user-images.githubusercontent.com/4451128/210881070-c487db2c-a3fd-4f03-90c5-5d70bdfc4b1d.png)

The pointer to the error points to the dds-footer-container because this the error is underneath it and with all your nested shadow DOMs we dont have an ability in the Chrome API to point too that particular component. So we point to the parent component. 

There does seem to be some this wrong here on our end as we are able to see an element with a for="input"
and 
id="input"
So there needs to be some investigation on our rules here.

**Comment by ErickRenteria** [comment] 2023-01-19 21:57
It looks good from my side. I'll wait for @zrebec to validate with our next deployment next week.

**Comment by ErickRenteria** [comment] 2023-02-06 18:06
Closing issue

**Closed by ErickRenteria** 2023-02-06 18:06 UTC
Labels: Bug, priority-1 (high), Ready for QA, development
